import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Weekly Schedule Analysis</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Weekly <span className="text-[hsl(280,100%,70%)]">Schedule</span> Analysis
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="dashboard/"
              target=""
            >
              <h3 className="text-2xl font-bold">Explore as a Guest →</h3>
              <div className="text-lg">
                Set dashboard parameters and filter to view live graphs, see what I 
                have done in my day, and explore how I organize me days.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="admin/"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Log In→</h3>
              <div className="text-lg">
                Only I, David, can login to categorize my actions.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
